In [2]:
import numpy as np

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [6]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [7]:
np.linspace(1,11,11)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.])

In [10]:
np.random.randint(0,10, (3,4))

array([[2, 4, 7, 9],
       [5, 8, 7, 6],
       [0, 2, 5, 2]])

In [29]:
np.random.seed(101)
arr = np.random.normal(0,1, (3,4))

In [31]:
arr

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053]])

In [19]:
arr.min()

-2.0181682440373918

In [20]:
arr.argmin()

8

In [21]:
arr.reshape((2,6))

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795,
        -0.31931804],
       [-0.84807698,  0.60596535, -2.01816824,  0.74012206,  0.52881349,
        -0.58900053]])

In [23]:
arr[0,3]

0.50382575382239358

In [30]:
arr[:,1]

array([ 0.62813271, -0.31931804,  0.74012206])

In [32]:
arr[:2,:2]

array([[ 2.70684984,  0.62813271],
       [ 0.65111795, -0.31931804]])

In [33]:
arr > 0

array([[ True,  True,  True,  True],
       [ True, False, False,  True],
       [False,  True,  True, False]], dtype=bool)

In [34]:
arr[arr > 0]

array([ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795,
        0.60596535,  0.74012206,  0.52881349])